services:
  app:
    image: gutsy4heart/literahouse:latest
    # build: 
        # context: .
        # dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - '8090:8080'
  
  postgres:
    image: postgres:latest
    container_name: postgres-container-murad
    environment:
        POSTGRES_PASSWORD: "postgres"
        POSTGRES_USER: "postgres"
        POSTGRES_DB: "literaDB"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgres/data
    restart: always

volumes:
  postgres-data:





