version: '3.8'

services:
  frontend:
    image: moguda/time-app-front-fbes1237ru
    restart: always
    ports:
      - '3000:3000'
  api:
    image: moguda/time-app-api-fbes1237ru
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - mysql
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time_db
    volumes:
      - mysql_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'

volumes:
    mysql_data: