name: CI/CD for time-app project

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20.19.3']
    steps:
      - name: Cloning repository
        uses: actions/checkout@v4

      - name: Install Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
      
      - name: API Dependency install
        working-directory: ./api
        run: npm install

        
      - name: Front Dependency install
        working-directory: ./frontend
        run: npm install
        
      - name: Run unit test
        working-directory: ./api
        run: npm test


  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest    

    strategy:
      matrix:
        node-version: ['20.19.3']
    
    steps:
      - name: Cloning repository
        uses: actions/checkout@v4

      - name: Docker login
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin

      - name: API image build and push to docker-hub
        run: |
          docker build -t ${{secrets.DOCKER_USERNAME}}/time-app-api-fbes1237ru ./api
          docker push ${{secrets.DOCKER_USERNAME}}/time-app-api-fbes1237ru
        
      - name: Frontend image build and push to docker-hub
        run: |
          docker build -t ${{secrets.DOCKER_USERNAME}}/time-app-front-fbes1237ru ./frontend
          docker push ${{secrets.DOCKER_USERNAME}}/time-app-front-fbes1237ru