name: CI/CD for Literahouse

on:
  push:
    branches: ["master"]

  workflow_dispatch:


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore and Build
        run: |
          dotnet restore LiteraHouse.sln
          dotnet build LiteraHouse.sln --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test LiteraHouse.sln --no-build --verbosity normal

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/literahouse .
          docker push ${{ secrets.DOCKER_USERNAME }}/literahouse


  deploy:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          port: 22
          script: |
            if [ ! -d "/app/literahouse/.git" ]; then
              git clone https://github.com/${{ github.repository }} /app/literahouse
            fi

            cd /app/literahouse
            git pull origin master

            docker compose pull
            docker compose down
            docker compose up -d
            docker image prune -f